services:
  - type: web
    name: infrapredictai-backend
    env: python
    runtime: python
    pythonVersion: "3.12.0"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
